#!/usr/bin/env bash
# Storyteller HTTPS setup — mkcert local CA + Caddy reverse proxy.
#
# Run ONCE on the Pi to enable HTTPS in front of the player web-ui
# (port 8090) and the admin (port 8080). Browsers gate
# `navigator.mediaDevices.getUserMedia` (= the voice page mic) behind
# a "secure context", which means HTTPS or localhost; plain LAN HTTP
# fails. This script terminates TLS in front of both backends so
# remote PCs/phones get a working voice mode.
#
# After running this:
#   • https://story.local/            → player text/voice/create
#   • https://story.local:8443/       → admin
#   • http://story.local/             → 301 redirect to https
#   • plain http://story.local:8090/  → still works (back-end direct)
#
# Re-run safely: idempotent — re-issues the server cert with whatever
# hostnames/IPs you currently have, overwrites the Caddyfile, restarts
# the service. The local-CA root cert is NOT regenerated unless
# /etc/storyteller/mkcert/rootCA*.pem are gone — devices that already
# trust it stay trusted.
set -euo pipefail

CA_DIR="/etc/storyteller/mkcert"
CERT="${CA_DIR}/storyteller-cert.pem"
KEY="${CA_DIR}/storyteller-key.pem"
CADDYFILE="/etc/caddy/Caddyfile"

err() { echo "[install_https] $*" >&2; }
log() { echo "[install_https] $*"; }

# Resolve the Pi's primary LAN IPv4 so we can include it in the cert.
# Without that, hitting the box by raw IP (https://192.168.178.71/)
# would fail the cert match in browsers that aren't using mDNS.
detect_ip() {
    hostname -I | awk '{ for (i = 1; i <= NF; i++) if ($i ~ /^[0-9.]+$/) { print $i; exit } }'
}
PRIMARY_IP="$(detect_ip)"
[[ -n "${PRIMARY_IP}" ]] || { err "no LAN IPv4 detected"; exit 2; }
log "primary LAN IP: ${PRIMARY_IP}"

if ! command -v caddy >/dev/null; then
    log "installing caddy + libnss3-tools…"
    sudo apt-get install -y caddy libnss3-tools
fi

if ! command -v mkcert >/dev/null; then
    log "downloading mkcert (arm64)…"
    arch="$(dpkg --print-architecture)"
    case "${arch}" in
        amd64)  asset="mkcert-v1.4.4-linux-amd64" ;;
        arm64)  asset="mkcert-v1.4.4-linux-arm64" ;;
        armhf)  asset="mkcert-v1.4.4-linux-arm" ;;
        *)      err "unsupported arch: ${arch}"; exit 2 ;;
    esac
    tmp=$(mktemp)
    curl -fsSL "https://github.com/FiloSottile/mkcert/releases/download/v1.4.4/${asset}" -o "${tmp}"
    sudo install -m 0755 "${tmp}" /usr/local/bin/mkcert
    rm -f "${tmp}"
fi

sudo mkdir -p "${CA_DIR}"
sudo chown pi:pi "${CA_DIR}"

if [[ ! -f "${CA_DIR}/rootCA.pem" ]]; then
    log "generating local CA + installing into system trust store…"
    sudo mkcert -install
    sudo cp /root/.local/share/mkcert/rootCA.pem "${CA_DIR}/"
    sudo cp /root/.local/share/mkcert/rootCA-key.pem "${CA_DIR}/"
    sudo chown -R pi:pi "${CA_DIR}"
    sudo chmod 600 "${CA_DIR}/rootCA-key.pem"
else
    log "reusing existing local CA at ${CA_DIR}/rootCA.pem"
fi

log "(re-)issuing server cert for story.local / storyteller.local / localhost / ${PRIMARY_IP}…"
# Make sure we can overwrite the previous key (which is chowned to
# root:caddy after the first run). mkcert runs as the invoking user.
sudo chown -R pi:pi "${CA_DIR}"
sudo chmod 600 "${CA_DIR}/rootCA-key.pem"
(
    cd "${CA_DIR}"
    CAROOT="${CA_DIR}" mkcert \
        -cert-file storyteller-cert.pem \
        -key-file storyteller-key.pem \
        story.local storyteller.local localhost 127.0.0.1 "${PRIMARY_IP}"
)
sudo chown root:caddy "${KEY}"
sudo chmod 0640 "${KEY}"

log "writing ${CADDYFILE}…"
sudo tee "${CADDYFILE}" >/dev/null <<EOF
# Storyteller HTTPS reverse proxy — generated by scripts/install_https.sh.
{
    auto_https off
    admin off
}

:80 {
    redir https://{host}{uri} permanent
}

:443 {
    tls ${CERT} ${KEY}
    encode gzip
    reverse_proxy localhost:8090 {
        flush_interval -1
    }
}

:8443 {
    tls ${CERT} ${KEY}
    encode gzip
    reverse_proxy localhost:8080 {
        flush_interval -1
    }
}
EOF

log "validating Caddyfile…"
sudo caddy validate --config "${CADDYFILE}" >/dev/null

log "restarting caddy…"
sudo systemctl enable caddy >/dev/null 2>&1 || true
sudo systemctl restart caddy

sleep 1
if ! systemctl is-active --quiet caddy; then
    err "caddy failed to start — check 'journalctl -u caddy -n 40'"
    exit 1
fi

log ""
log "✓ done. Smoke-test:"
log "    https://localhost/        (player text/voice)"
log "    https://localhost:8443/   (admin)"
log ""
log "Root CA for remote devices (install + trust on each phone/PC):"
log "    ${CA_DIR}/rootCA.pem"
log ""
log "Copy that file to your device and import it as a system-trusted"
log "root certificate (see docs/SETUP_HTTPS.md for per-device steps)."
